### ISSUE TITLE
Missing bower causes screens to not work

### ISSUE THREAD

**Issue by sedders123** [PeterJCLaw/srcomp-puppet#19]
While https://github.com/PeterJCLaw/srcomp-screens/commit/07706e351fec647f0c96dc8f00f1608eacf6be8b updates the screens to use yarn and https://github.com/PeterJCLaw/srcomp-puppet/commit/bc07b2be463018504b3fca038b4200a620e97fbd updates this puppet config to use yarn, the commit hasn't made it to [srobo/srcomp-screens](https://github.com/srobo/srcomp-screens) which is what gets cloned by default. Can we either merge the changes in srobo or change the default `comp_source` to be PeterJClaw

**Comment by PeterJCLaw** [comment]
In theory yes, however I don't appear to have write access to https://github.com/srobo/srcomp-screens.
I had actually thought I'd already changed the default clone to be my repos! They're canonical now, so ought to be the ones being cloned.

**Comment by PeterJCLaw** [comment]
Hrm, I'm confused. The default source _is_ already my GitHub: https://github.com/PeterJCLaw/srcomp-puppet/blob/bc07b2be463018504b3fca038b4200a620e97fbd/modules/compbox/manifests/init.pp#L3

**Comment by PeterJCLaw** [comment]
https://github.com/srobo/srcomp-screens now has the commits which move to `yarn`.
