### ISSUE TITLE
/srv has invalid permissions

### ISSUE THREAD

**Issue by WillB97** [PeterJCLaw/srcomp-puppet#21]
On recent raspbian and ubuntu the cloning the of the compstate fails with permission denied.

Setting the permissions of /srv before cloning fixes this.
```
    file { "/srv":
        ensure  => directory,
        owner   => 'srcomp',
        group   => 'www-data',
        mode    => '0775',
    }
```

**Comment by PeterJCLaw** [comment]
I believe this was fixed by 2d8a48c.
